language: java

jdk:
  - oraclejdk7

install: mvn install -DskipTests -Ptravis
script: mvn package -Ptravis
after_success:
  - mvn test cobertura:cobertura coveralls:cobertura -Pcoverall


notifications:
  email:
    - tyrcho@tyrcho.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3069b7e759e1d02548c1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


