language: java

jdk:
  - oraclejdk7

install: true
script: mvn package -Posx
after_success:
  - mvn test cobertura:cobertura coveralls:cobertura -Posx


notifications:
  email:
    - tyrcho@tyrcho.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3069b7e759e1d02548c1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


