language: java

jdk:
  - oraclejdk7

install: true
script: mvn package -Posx
after_success:
  - mvn test cobertura:cobertura coveralls:cobertura -Posx


notifications:
  email:
    - tyrcho@tyrcho.com
